/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

class A{
    A(){
    }

    void method(){
    }
}

class B extends A{
    B(){
    }

    void method(){
    }
}


public class App {

    static A m(A o){
        return o;
    }

    public static void main(String[] args) {


        // A x1 = new A();
        // int a = 5;
        // x1.method(a);

        A x1 = new A();
        A x2 = m(x1);
        
        B y1 = new B();
        A y2 = m(y1);

        x2.method();

        y2.method();
        // y1.method();
    }
}
